2021-01-11 12:11:25,904 - [test_01register.py-->line:44] - ERROR: 用例注册成功-带注册名成功
2021-01-11 12:11:26,374 - [test_01register.py-->line:44] - ERROR: 用例成功-不带用户名成功
2021-01-11 12:11:26,613 - [test_01register.py-->line:44] - ERROR: 用例不输入手机号成功
2021-01-11 12:11:26,843 - [test_01register.py-->line:44] - ERROR: 用例手机号长度10位成功
2021-01-11 12:11:27,093 - [test_01register.py-->line:44] - ERROR: 用例手机号长度12位成功
2021-01-11 12:11:27,333 - [test_01register.py-->line:44] - ERROR: 用例手机号含有非法字符成功
2021-01-11 12:11:27,623 - [test_01register.py-->line:44] - ERROR: 用例已注册过的手机号成功
2021-01-11 12:11:27,873 - [test_01register.py-->line:44] - ERROR: 用例密码7位成功
2021-01-11 12:11:28,103 - [test_01register.py-->line:44] - ERROR: 用例密码17位成功
2021-01-11 12:11:28,339 - [test_01register.py-->line:44] - ERROR: 用例不输入密码成功
2021-01-11 12:11:28,566 - [test_01register.py-->line:44] - ERROR: 用例注册名11位成功
2021-01-11 12:11:28,805 - [test_01register.py-->line:44] - ERROR: 用例类型输入非0，1内容成功
2021-01-11 12:11:29,095 - [test_01register.py-->line:40] - ERROR: 用例手机号为字符串类型失败
2021-01-11 12:11:29,095 - [test_01register.py-->line:41] - ERROR: 2 != 0
Traceback (most recent call last):
  File "C:\Users\HD\Desktop\qianchengdai\testcase\test_01register.py", line 33, in test_01_register
    self.assertEqual(expected["code"], res["code"])
  File "D:\测试\lib\unittest\case.py", line 852, in assertEqual
    assertion_func(first, second, msg=msg)
  File "D:\测试\lib\unittest\case.py", line 845, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 0
